useTabs: true
endOfLine: 'lf'
printWidth: 100
singleQuote: true
quoteProps: 'as-needed'
trailingComma: 'all'
arrowParens: 'avoid'
semi: true
jsxSingleQuote: true
plugins: ['prettier-plugin-tailwindcss']
